### ISSUE TITLE
Version 0.4 Completion Checklist

### ISSUE THREAD

**Issue by zelcion** [mapikit/meta-system#98]
## Description
Here We will describe all remaining topics to solve about MSYS v0.4 - Andromeda.

## Tasks
- [x] Add type verification for Addons Configurations values. Addons themselves already provide their configuration type through Object Definition, but this check is not being made.
- [x] Addons are not receiving the user configuration part of their setup only. Instead, they are receiving the whole addon object.
- [x] We should check if the `done()` function was called in the `"configure"` step of an Addon.
- [x] MSYS launch not thrown after fatal Addon configuration. It should return an error code > 0 if running on Node, and promise rejected if running on browser.
-----
More tasks will be added as we see fit.
